### ISSUE TITLE
Update config to use base path and type

### ISSUE THREAD

**Issue by adrianhall** [awslabs/aws-amplify-serverless-plugin#31]
Currently, we specify every single file and what type it is.  However, mostly, we just want to configure a client.  I'd suggest the following configuration types:

```
amplify:
  - base: ../android/app
    type: android
    appClient: AndroidUserPoolClient
    s3Bucket: UserFiles
  - base: ../ios/aws
     type: swift
    appClient: iOSUserPoolClient
    s3Bucket: UserFiles
  - base: ../web/src/aws
    type: react
    appClient: WebUserPoolClient
    s3Bucket: UserFiles
```

All of the code-gen and files should be placed "in the right place" for the designated app, with directories being created as needed.
