### ISSUE TITLE
BUG: saving javascript filetype throws an error (PR submitted)

### ISSUE THREAD

**Issue by rayjanwilson** [awslabs/aws-amplify-serverless-plugin#7]
when configuring the plugin for outputting a javascript formatted file, the following error is thrown:
`ERROR: amplify-plugin: Cannot load resources: nativeConfig is not defined`

Pull Request incoming

- A reproducible test case or series of steps
```yaml
amplify:
    - filename: ./aws-exports.js
      type: javascript
      appClient: WebUserPoolClient
```
- The version of our code being used
  - v0.1.0
- Any modifications you've made relevant to the bug
  - direct install from npm
- Anything unusual about your environment or deployment
  - os x: v10.13.6
  - serverless: v1.32.0
  - node.js: v10.12.0
